homeRedirect:
  path: "/"
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults: 
    route: home
    premanent: true
    keepQueryParams: true

CryptoRedirect:
  path: "/crypto"
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults: 
    route: crypto
    premanent: true
    keepQueryParams: true

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
